---
# http://www.htpcguides.com/spin-down-and-manage-hard-drive-power-on-raspberry-pi/

- name: "Install from source"
  ansible.builtin.include_tasks: from_source.yml
  when: ansible_facts["distribution"] == 'Debian' and ansible_facts["distribution_major_version"]|int < 11  # < bullseye

- name: "Enable default startup of hd-idle"
  ansible.builtin.lineinfile:
    dest: /etc/default/hd-idle
    create: true
    state: present
    line: "START_HD_IDLE=true"
    regexp: "^START_HD_IDLE="
    mode: '644'
  notify: "restart hd-idle"

- name: "Set default options of hd-idle"
  ansible.builtin.lineinfile:
    dest: /etc/default/hd-idle
    create: true
    state: present
    line: 'HD_IDLE_OPTS="-i 900 -l /var/log/hd-idle.log"'
    regexp: "^HD_IDLE_OPTS="
    mode: '644'
  notify: "restart hd-idle"
