---
# tasks file for hd-idle

- name: "Detect /proc/diskstats and decide wether we can install hd-idle"
  ansible.builtin.stat:
    path: /proc/diskstats
  register: _proc_diskstats

- name: "Make a system compatibility assertion"
  ansible.builtin.assert:
    that: "_proc_diskstats is defined"

- name: "Include installation tasks"
  ansible.builtin.include_tasks: hd_idle.yml
