---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: "$ANSIBLE_ROLES_PATH:$MOLECULE_PROJECT_DIRECTORY/..:$HOME/.ansible/roles"
scenario:
  name: default
